mklink /H C:\Users\Administrateur\.aliases C:\Users\Administrateur\workspace\dotfiles\.aliases
mklink /H C:\Users\Administrateur\.bash_prompt C:\Users\Administrateur\workspace\dotfiles\.bash_prompt
mklink /H C:\Users\Administrateur\.bashrc C:\Users\Administrateur\workspace\dotfiles\.bashrc
mklink /H C:\Users\Administrateur\.my_editorconfig C:\Users\Administrateur\workspace\dotfiles\.my_editorconfig
mklink /H C:\Users\Administrateur\.exports C:\Users\Administrateur\workspace\dotfiles\.exports
mklink /H C:\Users\Administrateur\.functions C:\Users\Administrateur\workspace\dotfiles\.functions
mklink /H C:\Users\Administrateur\.git_prompt C:\Users\Administrateur\workspace\dotfiles\.git_prompt
mklink /H C:\Users\Administrateur\.gitattributes C:\Users\Administrateur\workspace\dotfiles\.gitattributes
mklink /H C:\Users\Administrateur\.gitconfig C:\Users\Administrateur\workspace\dotfiles\.gitconfig
mklink /H C:\Users\Administrateur\.gitignore C:\Users\Administrateur\workspace\dotfiles\.gitignore
mklink /H C:\Users\Administrateur\.inputrc C:\Users\Administrateur\workspace\dotfiles\.inputrc
mklink /H C:\Users\Administrateur\.profile C:\Users\Administrateur\workspace\dotfiles\.profile
mklink /H C:\Users\Administrateur\.eslintrc C:\Users\Administrateur\workspace\dotfiles\.eslintrc
mklink /H C:\Users\Administrateur\.jscsrc C:\Users\Administrateur\workspace\dotfiles\.jscsrc
mklink /H C:\Users\Administrateur\.jshintrc C:\Users\Administrateur\workspace\dotfiles\.jshintrc
